events {
    worker_connections 1024;
}

http {
    upstream etudiant_service {
        server etudiant-service:8081;
    }

    upstream grading_service {
        server grading-service:8082;
    }

    upstream auth_service {
        server auth-service:3001;
    }

    upstream frontend_app {
        server frontend:3000;
    }

    server {
        listen 8080;

        location /api/etudiants {
            proxy_pass http://etudiant_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/departements {
            proxy_pass http://etudiant_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/notes {
            proxy_pass http://grading_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /auth {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
        }
    }
}
