apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.credentials.database }}
  POSTGRES_USER: {{ .Values.postgres.credentials.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.authService.jwtSecret }}
