apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=      # "postgres"
  POSTGRES_USER: cG9zdGdyZXM=    # "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
data:
  JWT_SECRET: c2VjcmV0X2p3dF90cmVzX2xvbmdfZXRfc2VjdXJpc2U=  # "secret_jwt_tres_long_et_securise"
